x=input()
if(x==1):
    print("one")
elif(x==2):
    print("two")
elif(x==3):
    print("three")
elif(x==4):
    print("four")
elif(x==5):
    print("five")
elif(x==6):
    print("six")
elif(x==7):
    print("seven")
elif(x==8):
    print("eight")
elif(x==9):
    print("nine")
elif(x==10):
    print("ten")
